### ISSUE TITLE
Add option to skip logging less important info.

### ISSUE THREAD

**Issue by Darkhax** [NeRdTheNed/jSus#1]
When running jsus on a directory I noticed a lot of log entries that weren't really important such as status messages for scanning each file and the JIJ support messages. It would be nice if there was an option to skip these and only log when a checker finds something. This would slightly improve performance and lower the buffer size requirement when scanning large archives with many JARs.

**Comment by NeRdTheNed** [comment]
Added in 488347a and set as default, along with the ability to restrict logging by sus level!
